- name: Find lock file and print
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:
  - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
    fetch:
      src: '/root/.bashrc'
      dest: /tmp/fetched/
      flat: yes
      fail_on_missing: no
