- name: Find lock file and print
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:
  - name: Fetch the file from the mwiapp01 to master
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: 'SELINUX=enforcing'
