- name: Find lock file and print
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:
  - name: Ansible find file examples
    find:
      paths: /home/mdtutorials2/findmodule/examples
      patterns: "*.txt"
      register: files_matched

  - debug:
      msg: "{{ files_matched.files }}"
