- name: Find lock file and print
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:
  - name: Ansible find file examples
    copy:
      src: "{{ item }}"
      dest: /tmp
    with_fileglob:
      - "/root/.bashrc*"
