- name: Find lock file and print
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:
  - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
    fetch:
      src: /var/lib/puppet/state/agent_disabled.lock
      dest: /tmp/fetched/
      fail_on_missing: no
