- name: use chage command
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:

    - name: Find users on the account and save it to a file.
      shell: 'cut -f 1 -d: /etc/passwd | sudo xargs -n 1 -I {} bash -c " echo {} ; chage -l {}" '
      register: result
            
    - name: Write linked_dirs file
      copy:
        content: '{{ result("\n") }}'
        dest: /tmp/chage
      delegate_to: localhost
