- name: use chage command
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:

    - name: Find users on the account and save it to a file.
      shell: 'awk -F':' '{ system("echo " $1 " && chage -l " $1)  }' /etc/passwd" '
      register: result 
      
    - local_action: copy content={{result}} dest=/root/sosa/output.txt
      delegate_to: localhost
