- name: Test Yum Update
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Yum clean all
      shell: yum clean all  
    - name: RHN check
      shell: rhn_check
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
