- name: Test Yum Update
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Upgrade all packages
      shell: yum clean all && rhn_check
      yum:
        name: '*'
        state: latest
