- name: Test Yum Update
  hosts: all
  become: true
  become_user: sysadm
  ssh_password: #15LpBd@Tt27(
  gather_facts: no
  tasks:
#    - name: Yum clean all
#      shell: yum clean all
#      args:
#        warn: false
#      become: true
#      any_errors_fatal: false
    - name: RHN profile sync
      command: rhn-profile-sync
      become: true
#    - name: RHN check
#      command: /usr/sbin/rhn_check
#    - name: Upgrade kernel
#      yum:
#        name: 'kernel*'
#        state: latest
#    - name: Upgrade everything else
#      yum:
#        name: '*'
#        state: latest
#        exclude: 'kernal*'

