- name: Test Yum Update
  hosts: all
  become: true 
  become_user: sysadm
  gather_facts: false
  tasks:
    - name: Yum clean all
      command: yum clean all
      args:
        warn: false
      become: true  
#    - name: RHN check
#      command: /usr/sbin/rhn_check
#    - name: Upgrade all packages
#      yum:
#        name: '*'
#        state: latest
