- name: Test Yum Update
  hosts: all
  become: yes
  become_user: sysadm
  gather_facts: false
  tasks:
    - name: Yum clean all
      commans: yum clean all  
    - name: RHN check
      command: /usr/sbin/rhn_check
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
