- name: Test Yum Update
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:
     
- name: shell command
    shell: 'cut -f 1 -d: /etc/passwd | sudo xargs -n 1 -I {} bash -c " echo {} ; chage -l {}"'
    register: myshell_output
            

