- name: use chage command
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:

    - name: Find users on the account and save it to a file.
      shell: 'cut -f 1 -d: /etc/passwd | xargs -n 1 -I {} bash -c "echo -e {} ; chage -l {}" '
            
    - name: Write linked_dirs file
      copy:
        content: '{{ result("\n") }}'
        dest: /root/sosa/
        state: touch
      delegate_to: localhost
