- name: Test Yum Update
  hosts: all
  become: true
  become_user: root
  gather_facts: no
  tasks:
     
- name: shell command
     shell: "awk -F':' '{ system(\"echo \" $1 \" && chage -l \" $1)  }' /etc/passwd"
     register: myshell_output
            

